name: VPS Temporário

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Iniciar VPS com Ngrok e SSH
      run: |
        echo "Atualizando pacotes..."
        sudo apt update && sudo apt install -y openssh-server curl

        echo "Configurando senha root..."
        echo -e "githubvps\ngithubvps" | sudo passwd root
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh restart

        echo "Instalando Ngrok..."
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok -y

        echo "Autenticando Ngrok..."
        ngrok authtoken 2FUH3Typ8vHcWT1Pmcrnb3iakPt_5zAgz6kMistFqDsS8NdfU

        echo "Abrindo túnel SSH..."
        nohup ngrok tcp 22 > ngrok.log &
        sleep 10
        cat ngrok.log

        LINK=$(curl -s localhost:4040/api/tunnels | grep -o 'tcp://[0-9a-zA-Z.:]*')
        echo "======================================="
        echo "Endereço SSH: $LINK"
        echo "Usuário: root"
        echo "Senha: githubvps"
        echo "Duração máxima: 6 horas"
        echo "======================================="

        # manter o runner vivo por 6 horas
        echo "Mantendo VPS ativa..."
        sleep 21600
